[project]
name = "dependencies-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.8.1",
    "mysql>=0.0.3",
    "mysql-connector-python>=9.3.0",
    "pymongo>=4.13.2",
    "requests>=2.32.4",
]
